// Colombian locations and areas reference
export const COLOMBIA_LOCATIONS = [
  {
    department: 'Antioquia',
    cities: ['Medellín', 'Envigado', 'Bello', 'Itagüí', 'Rionegro', 'Sabaneta'],
  },
  {
    department: 'Bogotá D.C. / Cundinamarca',
    cities: ['Bogotá D.C.', 'Chía', 'Soacha', 'Zipaquirá', 'Cajicá', 'Facatativá'],
  },
  {
    department: 'Valle del Cauca',
    cities: ['Cali', 'Palmira', 'Yumbo', 'Buenaventura', 'Buga', 'Tuluá'],
  },
  {
    department: 'Atlántico',
    cities: ['Barranquilla', 'Soledad', 'Puerto Colombia', 'Malambo', 'Sabanalarga'],
  },
  {
    department: 'Santander',
    cities: ['Bucaramanga', 'Floridablanca', 'San Gil', 'Girón', 'Piedecuesta'],
  },
  {
    department: 'Bolívar',
    cities: ['Cartagena', 'Turbaco', 'Arjona', 'Magangué'],
  },
  {
    department: 'Risaralda',
    cities: ['Pereira', 'Dosquebradas', 'Santa Rosa de Cabal'],
  },
  {
    department: 'Caldas',
    cities: ['Manizales', 'Villamaría', 'Chinchiná'],
  },
  {
    department: 'Magdalena',
    cities: ['Santa Marta', 'Ciénaga', 'Fundación'],
  },
  {
    department: 'Tolima',
    cities: ['Ibagué', 'Espinal', 'Melgar'],
  },
];

export const COLOMBIA_AREAS = [
  'Tecnología & Software',
  'Diseño & Creatividad',
  'Emprendimiento & Negocios',
  'Música & Entretenimiento',
  'Turismo & Gastronomía',
  'Fitness & Deporte',
  'Educación & Ciencia',
  'Café & Agroindustria',
  'Reciclaje & Sostenibilidad',
];

export const MOCK_COLOMBIAN_USERS = [
  // ==========================================
  // 1. MIS AMIGOS (20+ amigos activos)
  // ==========================================
  {
    id: 'user_col_1',
    name: 'Valentina Restrepo',
    username: 'valen_restrepo',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    department: 'Antioquia',
    city: 'Medellín',
    area: 'Tecnología & Software',
    bio: 'Frontend Dev & entusiasta de Vue y Tailwind. Disfrutando del clima de El Poblado 🌿☕',
    work: 'Tech Lead en Ruta N',
    education: 'Universidad de Antioquia',
    mutualFriends: 14,
    status: 'friend',
    isOnline: true,
  },
  {
    id: 'user_col_2',
    name: 'Mateo Gómez Caicedo',
    username: 'mateogomez',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    department: 'Bogotá D.C. / Cundinamarca',
    city: 'Bogotá D.C.',
    area: 'Emprendimiento & Negocios',
    bio: 'Founder de fintech colombiana. Fanático del ciclismo por los Cerros Orientales 🚴‍♂️🏔️',
    work: 'Co-founder en PagosÁgiles',
    education: 'Universidad de Los Andes',
    mutualFriends: 22,
    status: 'friend',
    isOnline: true,
  },
  {
    id: 'user_col_3',
    name: 'Camila Ospina',
    username: 'cami_ospina',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80',
    department: 'Valle del Cauca',
    city: 'Cali',
    area: 'Diseño & Creatividad',
    bio: 'Brand designer y amante de la salsa caleña y la fotografía urbana 🎨🎶',
    work: 'Directora de Arte en Estudio Caña',
    education: 'Universidad del Valle',
    mutualFriends: 9,
    status: 'friend',
    isOnline: false,
  },
  {
    id: 'user_col_4',
    name: 'Sebastián Char',
    username: 'sebaskchar',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    department: 'Atlántico',
    city: 'Barranquilla',
    area: 'Música & Entretenimiento',
    bio: 'Productor musical caribeño. Conectando beats latinos con el mundo entero 🥁🌊',
    work: 'Sound Producer en Caribe Records',
    education: 'Universidad del Norte',
    mutualFriends: 18,
    status: 'friend',
    isOnline: true,
  },
  {
    id: 'user_col_5',
    name: 'Daniela Forero',
    username: 'dani_forero',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    department: 'Santander',
    city: 'Bucaramanga',
    area: 'Educación & Ciencia',
    bio: 'Investigadora en biotecnología y energías renovables en la Ciudad Bonita 🔬☀️',
    work: 'Docente investigadora en UIS',
    education: 'Universidad Industrial de Santander',
    mutualFriends: 7,
    status: 'friend',
    isOnline: false,
  },
  {
    id: 'user_col_6',
    name: 'Andrés Felipe Morales',
    username: 'andresf_morales',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    department: 'Antioquia',
    city: 'Envigado',
    area: 'Café & Agroindustria',
    bio: 'Catador de café especial de origen andino y barista certificado ☕🍃',
    work: 'Owner en Café de la Serranía',
    education: 'Escuela Nacional del Café',
    mutualFriends: 11,
    status: 'friend',
    isOnline: true,
  },
  {
    id: 'user_col_7',
    name: 'Elena Rostova',
    username: 'elena_r',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    department: 'Antioquia',
    city: 'Medellín',
    area: 'Turismo & Gastronomía',
    bio: 'Fotógrafa de viajes & Paisajismo alpino. Buscando siempre la mejor luz 🏔️📸',
    work: 'Fotógrafa Documental',
    education: 'Universidad de Antioquia',
    mutualFriends: 29,
    status: 'friend',
    isOnline: true,
  },
  {
    id: 'user_col_8',
    name: 'Alejandro Morales',
    username: 'alexmorales',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    department: 'Valle del Cauca',
    city: 'Cali',
    area: 'Tecnología & Software',
    bio: 'Software Engineer | Entusiasta del open source, café de especialidad y TypeScript ☕💻',
    work: 'Senior Frontend Engineer',
    education: 'Universidad del Valle',
    mutualFriends: 21,
    status: 'friend',
    isOnline: true,
  },
  {
    id: 'user_col_9',
    name: 'Sofía Valenzuela',
    username: 'sofi_val',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80',
    department: 'Santander',
    city: 'Bucaramanga',
    area: 'Diseño & Creatividad',
    bio: 'Arquitecta de interiores sustentables. Amante del arte botánico 🌱🏛️',
    work: 'Directora en EcoEspacios',
    education: 'Universidad Industrial de Santander',
    mutualFriends: 16,
    status: 'friend',
    isOnline: false,
  },
  {
    id: 'user_col_10',
    name: 'Angel Bermudez',
    username: 'angel_bermudez',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=1200&q=80',
    department: 'Antioquia',
    city: 'Rionegro',
    area: 'Reciclaje & Sostenibilidad',
    bio: 'Coordinador ambiental en Antioquia Circular. Transformando residuos en recursos ♻️🌎',
    work: 'Coordinador de Proyectos Verdes',
    education: 'Universidad EAFIT',
    mutualFriends: 34,
    status: 'friend',
    isOnline: true,
  },
  {
    id: 'user_col_11',
    name: 'Jeferson Jose Bello H.',
    username: 'jeferson_bello',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    department: 'Bogotá D.C. / Cundinamarca',
    city: 'Bogotá D.C.',
    area: 'Tecnología & Software',
    bio: 'Desarrollador Web y aficionado a la naturaleza 🌿💻',
    work: 'Frontend Developer',
    education: 'Universidad Nacional de Colombia',
    mutualFriends: 42,
    status: 'friend',
    isOnline: true,
  },
  {
    id: 'user_col_12',
    name: 'Natalia Botero',
    username: 'nati_botero',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80',
    department: 'Antioquia',
    city: 'Medellín',
    area: 'Fitness & Deporte',
    bio: 'Instructora de Yoga y escaladora de roca en El Peñol 🧘‍♀️🧗‍♀️',
    work: 'Fundadora en Prana Studio',
    education: 'CES Medellín',
    mutualFriends: 19,
    status: 'friend',
    isOnline: true,
  },
  {
    id: 'user_col_13',
    name: 'Carlos Andrés Trujillo',
    username: 'carlos_trujillo',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?auto=format&fit=crop&w=1200&q=80',
    department: 'Risaralda',
    city: 'Pereira',
    area: 'Café & Agroindustria',
    bio: 'Productor de cafés de alta gama en Dosquebradas y Santa Rosa 🍒☕',
    work: 'Gerente en Café Risaralda',
    education: 'Universidad Tecnológica de Pereira',
    mutualFriends: 15,
    status: 'friend',
    isOnline: false,
  },
  {
    id: 'user_col_14',
    name: 'Manuela Cifuentes',
    username: 'manu_cifuentes',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
    department: 'Caldas',
    city: 'Manizales',
    area: 'Educación & Ciencia',
    bio: 'Divulgadora científica sobre biodiversidad en los Nevados 🌋🦅',
    work: 'Bióloga en Parques Nacionales',
    education: 'Universidad de Caldas',
    mutualFriends: 23,
    status: 'friend',
    isOnline: true,
  },
  {
    id: 'user_col_15',
    name: 'Jorge Eliécer Salazar',
    username: 'jorge_salazar',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80',
    department: 'Bolívar',
    city: 'Cartagena',
    area: 'Turismo & Gastronomía',
    bio: 'Guía de expediciones ecológicas en Islas del Rosario 🚤🏝️',
    work: 'Director de Ecoturismo Caribe',
    education: 'Universidad de Cartagena',
    mutualFriends: 11,
    status: 'friend',
    isOnline: false,
  },
  {
    id: 'user_col_16',
    name: 'Diana Patricia Meza',
    username: 'diana_meza',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    department: 'Magdalena',
    city: 'Santa Marta',
    area: 'Reciclaje & Sostenibilidad',
    bio: 'Liderando limpiezas de playas y protección de corales en el Tayrona 🌊🐠',
    work: 'Fundadora de EcoMar Santa Marta',
    education: 'Universidad del Magdalena',
    mutualFriends: 27,
    status: 'friend',
    isOnline: true,
  },
  {
    id: 'user_col_17',
    name: 'Diego Fernando Rincón',
    username: 'diego_rincon',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    department: 'Tolima',
    city: 'Ibagué',
    area: 'Música & Entretenimiento',
    bio: 'Guitarrista y productor musical en la Capital Musical de Colombia 🎸🎼',
    work: 'Productor en TolimaSound',
    education: 'Conservatorio del Tolima',
    mutualFriends: 8,
    status: 'friend',
    isOnline: true,
  },

  // ==========================================
  // 2. SOLICITUDES DE AMISTAD RECIBIDAS (6 solicitudes)
  // ==========================================
  {
    id: 'user_col_req_1',
    name: 'Mariana Zuluaga',
    username: 'mari_zuluaga',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?auto=format&fit=crop&w=1200&q=80',
    department: 'Antioquia',
    city: 'Medellín',
    area: 'Diseño & Creatividad',
    bio: 'Diseñadora de moda sostenible y fotógrafa editorial en el Valle de Aburrá ✨🧵',
    work: 'Directora Creativa en Telar Verde',
    education: 'UPB Medellín',
    mutualFriends: 15,
    status: 'request_received',
    timestamp: 'Hace 40 minutos',
    isOnline: true,
  },
  {
    id: 'user_col_req_2',
    name: 'Juan Pablo Arango',
    username: 'juanpa_arango',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1200&q=80',
    department: 'Risaralda',
    city: 'Pereira',
    area: 'Tecnología & Software',
    bio: 'Mobile Engineer (Android & Flutter). Construyendo apps para el Eje Cafetero 📱☕',
    work: 'Senior Android Engineer',
    education: 'Universidad Tecnológica de Pereira',
    mutualFriends: 8,
    status: 'request_received',
    timestamp: 'Hace 2 horas',
    isOnline: true,
  },
  {
    id: 'user_col_req_3',
    name: 'Isabella Quintana',
    username: 'isa_quintana',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
    department: 'Bolívar',
    city: 'Cartagena',
    area: 'Turismo & Gastronomía',
    bio: 'Chef ejecutiva y embajadora culinaria de la Ciudad Amurallada 🍤🌴',
    work: 'Chef Propietaria en Sabores del Baluarte',
    education: 'Gato Dumas Colombia',
    mutualFriends: 6,
    status: 'request_received',
    timestamp: 'Ayer',
    isOnline: false,
  },
  {
    id: 'user_col_req_4',
    name: 'Mauricio Galeano',
    username: 'mauro_galeano',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80',
    department: 'Bogotá D.C. / Cundinamarca',
    city: 'Bogotá D.C.',
    area: 'Emprendimiento & Negocios',
    bio: 'Consultor de impacto ambiental y bonos de carbono para empresas 📊🌱',
    work: 'Senior Partner en CarbonoCero',
    education: 'Universidad del Rosario',
    mutualFriends: 18,
    status: 'request_received',
    timestamp: 'Hace 3 horas',
    isOnline: true,
  },
  {
    id: 'user_col_req_5',
    name: 'Lucía Fernández',
    username: 'lucia_fdz',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    department: 'Valle del Cauca',
    city: 'Palmira',
    area: 'Educación & Ciencia',
    bio: 'Ingeniera ambiental investigando agroforestería sostenible en el Valle 🌾🌿',
    work: 'Investigadora en CIAT',
    education: 'Universidad Nacional Sede Palmira',
    mutualFriends: 12,
    status: 'request_received',
    timestamp: 'Hace 5 horas',
    isOnline: false,
  },

  // ==========================================
  // 3. SUGERENCIAS PARA AGREGAR AMIGOS (15+ personas)
  // ==========================================
  {
    id: 'user_col_sug_1',
    name: 'Santiago Bernal',
    username: 'santi_bernal',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&w=1200&q=80',
    department: 'Bogotá D.C. / Cundinamarca',
    city: 'Chía',
    area: 'Tecnología & Software',
    bio: 'DevOps & Cloud Architect en AWS. Aficionado al senderismo y los podcasts tech ☁️🎙️',
    work: 'Cloud Solutions Lead',
    education: 'Universidad Nacional de Colombia',
    mutualFriends: 19,
    status: 'suggestion',
    isOnline: true,
  },
  {
    id: 'user_col_sug_2',
    name: 'Laura Sofía Montoya',
    username: 'laura_montoya',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?auto=format&fit=crop&w=1200&q=80',
    department: 'Antioquia',
    city: 'Rionegro',
    area: 'Fitness & Deporte',
    bio: 'Maratonista y entrenadora deportiva en el Oriente Antioqueño 🏃‍♀️🏅',
    work: 'Head Coach en RunClub Colombia',
    education: 'Politécnico Jaime Isaza Cadavid',
    mutualFriends: 12,
    status: 'suggestion',
    isOnline: true,
  },
  {
    id: 'user_col_sug_3',
    name: 'Nicolás Pineda',
    username: 'nico_pineda',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80',
    department: 'Caldas',
    city: 'Manizales',
    area: 'Café & Agroindustria',
    bio: 'Ingeniero agrónomo especializado en fincas cafetaleras sostenibles 🌿☕',
    work: 'Director Agro en Cenicafé',
    education: 'Universidad de Caldas',
    mutualFriends: 5,
    status: 'suggestion',
    isOnline: false,
  },
  {
    id: 'user_col_sug_4',
    name: 'Estefanía Barón',
    username: 'estefa_baron',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80',
    department: 'Atlántico',
    city: 'Barranquilla',
    area: 'Emprendimiento & Negocios',
    bio: 'Consultora de eCommerce y aceleradora de startups de la costa 🚀📈',
    work: 'Managing Partner en CaribeVentures',
    education: 'Universidad del Norte',
    mutualFriends: 16,
    status: 'suggestion',
    isOnline: true,
  },
  {
    id: 'user_col_sug_5',
    name: 'Carlos Eduardo Vivas',
    username: 'carlos_vivas',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    department: 'Valle del Cauca',
    city: 'Palmira',
    area: 'Tecnología & Software',
    bio: 'Data Scientist & Machine Learning Developer. Apasionado del ajedrez 🤖♟️',
    work: 'Lead Data Scientist',
    education: 'Universidad Icesi',
    mutualFriends: 8,
    status: 'suggestion',
    isOnline: true,
  },
  {
    id: 'user_col_sug_6',
    name: 'Gabriela Cárdenas',
    username: 'gabi_cardenas',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80',
    department: 'Santander',
    city: 'San Gil',
    area: 'Turismo & Gastronomía',
    bio: 'Guía de deportes extremos y turismo ecológico en el Cañón del Chicamocha 🛶🧗‍♂️',
    work: 'CEO en Aventura Santander',
    education: 'SENA Santander',
    mutualFriends: 4,
    status: 'suggestion',
    isOnline: false,
  },
  {
    id: 'user_col_sug_7',
    name: 'Felipe Henao',
    username: 'pipe_henao',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80',
    department: 'Antioquia',
    city: 'Medellín',
    area: 'Tecnología & Software',
    bio: 'Desarrollador de Smart Contracts y soluciones blockchain verdes ⛓️🌱',
    work: 'Blockchain Lead en CryptoAndes',
    education: 'EAFIT',
    mutualFriends: 17,
    status: 'suggestion',
    isOnline: true,
  },
  {
    id: 'user_col_sug_8',
    name: 'Paula Andrea Gómez',
    username: 'pau_gomez',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80',
    department: 'Bogotá D.C. / Cundinamarca',
    city: 'Bogotá D.C.',
    area: 'Educación & Ciencia',
    bio: 'Bióloga marina y educadora ambiental. Cuidando los páramos y manglares de Colombia 🌊🐋',
    work: 'Investigadora en Instituto Humboldt',
    education: 'Universidad Nacional de Colombia',
    mutualFriends: 25,
    status: 'suggestion',
    isOnline: true,
  },
  {
    id: 'user_col_sug_9',
    name: 'Julián David Castro',
    username: 'julian_castro',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80',
    department: 'Valle del Cauca',
    city: 'Cali',
    area: 'Música & Entretenimiento',
    bio: 'Percusionista, compositor y entusiasta de la economía circular en festivales 🥁🌴',
    work: 'Director Musical en CaliSuena',
    education: 'Instituto Departamental de Bellas Artes',
    mutualFriends: 13,
    status: 'suggestion',
    isOnline: false,
  },
  {
    id: 'user_col_sug_10',
    name: 'Sara Lucía Quintana',
    username: 'sara_quintana',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    department: 'Antioquia',
    city: 'Sabaneta',
    area: 'Diseño & Creatividad',
    bio: 'Diseñadora de empaques biodegradables a partir de fibra de caña y fique 🌾📦',
    work: 'EcoPackaging Lead',
    education: 'Universidad Pontificia Bolivariana',
    mutualFriends: 22,
    status: 'suggestion',
    isOnline: true,
  },
  {
    id: 'user_col_sug_11',
    name: 'Ricardo Vélez',
    username: 'richi_velez',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1200&q=80',
    department: 'Risaralda',
    city: 'Pereira',
    area: 'Tecnología & Software',
    bio: 'Arquitecto de software y promotor de comunidades tech en el Eje Cafetero ☕🚀',
    work: 'Staff Engineer',
    education: 'UTP',
    mutualFriends: 14,
    status: 'suggestion',
    isOnline: true,
  },
  {
    id: 'user_col_sug_12',
    name: 'Valeria Cárdenas',
    username: 'vale_cardenas',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?auto=format&fit=crop&w=1200&q=80',
    department: 'Bogotá D.C. / Cundinamarca',
    city: 'Zipaquirá',
    area: 'Turismo & Gastronomía',
    bio: 'Chef pastelera y promotora del turismo gastronómico en la sabana de Bogotá 🍰🍓',
    work: 'Head Baker en La Sabana Dulce',
    education: 'SENA Gastronomía',
    mutualFriends: 10,
    status: 'suggestion',
    isOnline: false,
  },
  {
    id: 'user_col_sug_13',
    name: 'Alonso Pardo',
    username: 'alonso_pardo',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    coverImage: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=1200&q=80',
    department: 'Santander',
    city: 'Floridablanca',
    area: 'Reciclaje & Sostenibilidad',
    bio: 'Ingeniero de reciclaje industrial y valorización de chatarra electrónica ♻️🔌',
    work: 'Director Técnico en EcoRAEE',
    education: 'Universidad Industrial de Santander',
    mutualFriends: 19,
    status: 'suggestion',
    isOnline: true,
  },
];

export const radarService = {
  async fetchUsers() {
    return Promise.resolve([...MOCK_COLOMBIAN_USERS]);
  },
};
